version: '3.2'
services:
  sentimentalyzer:
    build: ../
    environment:
      - PORT=8123
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    # pass custom command to start Cypress otherwise it will use the entrypoint
    # specified in the Cypress Docker image.
    # also pass "--project <folder>" so that when Cypress opens
    # it can find file "cypress.json" and show integration specs
    # https://on.cypress.io/command-line#cypress-open
    entrypoint: cypress open --project /e2e
    depends_on:
      - sentimentalyzer
    environment:
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
      # pass environment variable DISPLAY if you need
      # to show Cypress GUI on the host system
      # typically you get the IP of the host system
      # and set DISPLAY
      #   IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
      #   DISPLAY=$IP:0
      # run docker-compose with
      #   DISPLAY=$IP:0 docker-compose up --exit-code-from cypress
      - DISPLAY
    working_dir: /e2e
    volumes:
      - ./:/e2e
      # allow connecting from Docker container to
      # external XVFB server running on the host machine
      # see https://sourabhbajaj.com/blog/2017/02/07/gui-applications-docker-mac/
      - /tmp/.X11-unix:/tmp/.X11-unix
